name: First workflow
on: push

jobs:
  build:
    name: Yeah
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./action-a
        with:
          MY_NAME: "Roger"
