name: test workflow
run-name: ${{ github.actor }} called this workflow
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "this is the first step of my job, let's check out the repository.."
    - name: check out code
      uses: actions/checkout@v4
    - name: display super secret
      env:
        top-secret: ${{ secrets.TOP-SECRET }}
      run: echo "${top-secret}" | base64
    - name: list files
      run: |
        ls ${{ github.workspace }}