name: publish
run-name: build is being published
on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches:
    - main
jobs:
  publish-first:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        name: makefile-digests-${{ github.sha }}
    - run: cat makefile-digests-${{ github.sha }}
    - name: debug
      env:
        event: ${{ toJSON(github.event) }}
      run: echo "${event}"
